Unconditionally reload rsyslog config.
It's tricky to identify the wheezy->jessie upgrade, so don't try
to be clever here.

diff --git a/jessie/postinst b/jessie/postinst
--- a/jessie/postinst
+++ b/jessie/postinst
@@ -55,11 +55,8 @@ EOF
             [ -f /etc/piaware ] && mv /etc/piaware /etc/piaware.old
         fi
 
-        # reload rsyslog configuration if we installed some new config
-        if dpkg --compare-versions "$2" lt "3.0"; then
-            echo "Reloading rsyslog configuration.." >&2
-            invoke-rc.d rsyslog force-reload || echo "Warning: rsyslog failed to reload"
-        fi
+        echo "Reloading rsyslog configuration.." >&2
+        invoke-rc.d rsyslog force-reload || echo "Warning: rsyslog failed to reload"
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
